yarnPath: .yarn/releases/yarn-4.10.3.cjs

packageExtensions:
  'vite-plugin-vue-devtools@*':
    peerDependencies:
      vue: '*'

  '@vue/test-utils@*':
    peerDependencies:
      '@vue/compiler-dom': '*'
      '@vue/server-renderer': '*'
      vue: '*'

  '@testing-library/vue@*':
    peerDependencies:
      '@vue/compiler-dom': '*'
      '@vue/server-renderer': '*'
